name: Deploy learning-journal

on:
  push:
    branches:
      - main # Or your default branch, e.g., 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Using the latest recommended version

      - name: Deploy files via SCP
        uses: appleboy/scp-action@v0.1.7 # Specific version you were using

        with:
          host: ${{ secrets.SERVER_HOST }}
          username: admin_pablo
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "./*" # Deploy all files and folders from the repository root
          target: "/var/www/learning-journal" # Your specific target directory on the server
