name: Deploy learning-journal

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: admin_pablo
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./**"  # deploy all files in the repo root and subfolders
          target: "/var/www/learning-journal"
